sudo: required

services:
  - docker

before_install:
  - docker build -t lukeomalley/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lukeomalley/docker-react npm run test -- --coverage
